# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

#steps:
#- script: echo Hello, world!
#  displayName: 'Run a one-line script'

steps:
- task: Docker@2
  displayName: 'Run Image'
  inputs:
    containerRegistry: 'MyConnection_Rwik'
    command: run
    arguments: ' --rm --env-file /home/azureuser/env.list -v $(Agent.BuildDirectory)/s:/wa  hclcr.io/appscan/appscan-src-cli:10.2.0 script /wa/cli.script'
  env:
    AS_INSTALL_MODE: standalone
    AS_LICENSE_TYPE: CLS
    AS_LICENSE_SERVER_ID: PUGAU36NN7RX
    AS_LICENSE_SERVER: hclsoftware
- task: Docker@0
  displayName: Clean
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryConnection: 'MyConnection_Rwik'
    action: 'Run a Docker command'
    customCommand: 'system prune -a -f'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
