name: "HCL AppScan Source Action"
on:
  workflow_dispatch #manually trigger the action 
jobs:
  scan:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Load docker image
        uses: docker://hclcr.io/appscan/appscan-src-cli:10.2.0
        
      #- name: Run docker command for SAST scan
      #  uses: docker run --rm --env-file /vj_space/env.list -v /vj_space/wa:/wa hclcr.io/appscan/appscan-src-cli:10.2.0  script cli.script


        
      #- name: Remove docker image loaded in this action
      #  uses: docker rmi hclcr.io/appscan/appscan-src-cli:10.2.0     
        
